# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rules_engine}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Douglas"]
  s.date = %q{2010-07-21}
  s.description = %q{Rules engine}
  s.email = %q{dougo.chris@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "VERSION",
     "init.rb",
     "lib/rules_engine.rb",
     "lib/rules_engine/cache.rb",
     "lib/rules_engine/discovery.rb",
     "lib/rules_engine/process/auditor.rb",
     "lib/rules_engine/process/auditor/db_auditor.rb",
     "lib/rules_engine/process/runner.rb",
     "lib/rules_engine/process/runner/db_runner.rb",
     "lib/rules_engine/publish/publisher.rb",
     "lib/rules_engine/publish/publisher/db_publisher.rb",
     "lib/rules_engine/rule/definition.rb",
     "lib/rules_engine/rule/outcome.rb",
     "lib/rules_engine_view.rb",
     "lib/rules_engine_view/alerts.rb",
     "lib/rules_engine_view/boxes.rb",
     "lib/rules_engine_view/buttons.rb",
     "lib/rules_engine_view/defer.rb",
     "lib/rules_engine_view/form_builder.rb",
     "lib/rules_engine_view/form_fields.rb",
     "lib/rules_engine_view/form_styles.rb",
     "lib/rules_engine_view/model_loader.rb",
     "lib/rules_engine_view/navigate.rb",
     "rails_generators/manifests/complex.yml",
     "rails_generators/manifests/rules_engine.rb",
     "rails_generators/manifests/rules_engine.yml",
     "rails_generators/manifests/simple.yml",
     "rails_generators/rules_engine_generator.rb",
     "spec/railsenv/app/controllers/application_controller.rb",
     "spec/railsenv/app/rules/mock_rule.rb",
     "spec/railsenv/config/boot.rb",
     "spec/railsenv/config/database.yml",
     "spec/railsenv/config/environment.rb",
     "spec/railsenv/config/environments/development.rb",
     "spec/railsenv/config/environments/production.rb",
     "spec/railsenv/config/environments/test.rb",
     "spec/railsenv/config/initializers/backtrace_silencers.rb",
     "spec/railsenv/config/initializers/inflections.rb",
     "spec/railsenv/config/initializers/mime_types.rb",
     "spec/railsenv/config/initializers/new_rails_defaults.rb",
     "spec/railsenv/config/initializers/session_store.rb",
     "spec/railsenv/config/locales/en.yml",
     "spec/railsenv/config/routes.rb",
     "spec/railsenv/db/test.sqlite3",
     "spec/railsenv/log/debug.log",
     "spec/railsenv/log/empty.txt",
     "spec/railsenv/log/test.log",
     "spec/rcov.opts",
     "spec/rules_engine/cache_spec.rb",
     "spec/rules_engine/discovery_spec.rb",
     "spec/rules_engine/process/auditor/db_auditor_spec.rb",
     "spec/rules_engine/process/auditor_spec.rb",
     "spec/rules_engine/process/runner/db_runner_spec.rb",
     "spec/rules_engine/process/runner_spec.rb",
     "spec/rules_engine/publish/publisher/db_publisher_spec.rb",
     "spec/rules_engine/publish/publisher_spec.rb",
     "spec/rules_engine/rule/definition_spec.rb",
     "spec/rules_engine_view/alerts_spec.rb",
     "spec/rules_engine_view/boxes_spec.rb",
     "spec/rules_engine_view/buttons_spec.rb",
     "spec/rules_engine_view/defer_spec.rb",
     "spec/rules_engine_view/form_builder_fields_spec.rb",
     "spec/rules_engine_view/form_builder_spec.rb",
     "spec/rules_engine_view/form_fields_spec.rb",
     "spec/rules_engine_view/form_styles_spec.rb",
     "spec/rules_engine_view/model_loader_spec.rb",
     "spec/rules_engine_view/navigate_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/dougochris/rules_engine_view}
  s.post_install_message = %q{
      *** RUN script/generate rules_engine
    }
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rules engine}
  s.test_files = [
    "spec/railsenv/app/controllers/application_controller.rb",
     "spec/railsenv/app/rules/mock_rule.rb",
     "spec/railsenv/config/boot.rb",
     "spec/railsenv/config/environment.rb",
     "spec/railsenv/config/environments/development.rb",
     "spec/railsenv/config/environments/production.rb",
     "spec/railsenv/config/environments/test.rb",
     "spec/railsenv/config/initializers/backtrace_silencers.rb",
     "spec/railsenv/config/initializers/inflections.rb",
     "spec/railsenv/config/initializers/mime_types.rb",
     "spec/railsenv/config/initializers/new_rails_defaults.rb",
     "spec/railsenv/config/initializers/session_store.rb",
     "spec/railsenv/config/routes.rb",
     "spec/rules_engine/cache_spec.rb",
     "spec/rules_engine/discovery_spec.rb",
     "spec/rules_engine/process/auditor/db_auditor_spec.rb",
     "spec/rules_engine/process/auditor_spec.rb",
     "spec/rules_engine/process/runner/db_runner_spec.rb",
     "spec/rules_engine/process/runner_spec.rb",
     "spec/rules_engine/publish/publisher/db_publisher_spec.rb",
     "spec/rules_engine/publish/publisher_spec.rb",
     "spec/rules_engine/rule/definition_spec.rb",
     "spec/rules_engine_view/alerts_spec.rb",
     "spec/rules_engine_view/boxes_spec.rb",
     "spec/rules_engine_view/buttons_spec.rb",
     "spec/rules_engine_view/defer_spec.rb",
     "spec/rules_engine_view/form_builder_fields_spec.rb",
     "spec/rules_engine_view/form_builder_spec.rb",
     "spec/rules_engine_view/form_fields_spec.rb",
     "spec/rules_engine_view/form_styles_spec.rb",
     "spec/rules_engine_view/model_loader_spec.rb",
     "spec/rules_engine_view/navigate_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

