#!/bin/sh

for plan in "install" "layout" "simple" "complex"; do
  echo "********************"  
  echo "$plan"  
  cd generators
  ~/Workspace/chris/gfm/gfm ~/Temp/MyCoolNewApp $plan
  if [ "$?" != "0" ]; then
    echo "******************** ******************** failed"
  fi
  cd ..
done
