#!/bin/sh

for plan in "rules_engine_install" "rules_engine_layout" "rules_engine_simple" "rules_engine_complex"; do
  echo "********************"  
  echo "$plan"  
  bam ~/Temp/MyCoolNewApp $plan
  if [ "$?" != "0" ]; then
    echo "******************** ******************** failed"
  fi
done
