source 'http://rubygems.org'

gem 'rails', '3.0.1'

gem 'sqlite3-ruby', :require => 'sqlite3'

# Setting the path now uses our development gem
gem 'rules_view'
gem 'rules_engine', :path => '../../'
gem 'will_paginate', '>= 3.0.pre2'
gem 'acts_as_list'

gem 'sqlite3-ruby', :require => 'sqlite3'

group :development, :test do
  gem "rspec-rails"
  gem "webrat"
  gem "faker"
  gem "machinist"

 gem 'rcov'
end