class ApplicationManifest
  def self.populate_record(m, rule_name)

    %W(
       config/initializers
       db/migrate
       doc
       public/javascripts/rules_engine
       public/stylesheets
       public/stylesheets/rules_engine
       public/stylesheets/rules_engine/blueprint
       public/stylesheets/rules_engine/blueprint/plugins
       public/stylesheets/rules_engine/blueprint/plugins/buttons
       public/stylesheets/rules_engine/blueprint/plugins/buttons/icons
       public/stylesheets/rules_engine/blueprint/plugins/fancy-type
       public/stylesheets/rules_engine/blueprint/plugins/link-icons
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons
       public/stylesheets/rules_engine/blueprint/plugins/rtl
       public/stylesheets/rules_engine/blueprint/src
       public/stylesheets/rules_engine/fancybox
       public/stylesheets/rules_engine/images
       public/stylesheets/rules_engine/images/re_view_box
       public/stylesheets/rules_engine/images/re_view_button
       public/stylesheets/rules_engine/images/re_view_error
       public/stylesheets/rules_engine/images/re_view_navigate
       public/stylesheets/rules_engine/images/rules_engine
       public/stylesheets/rules_engine/images/rules_engine/re_common
       public/stylesheets/rules_engine/images/rules_engine/re_history
       public/stylesheets/rules_engine/images/rules_engine/re_plan
       public/stylesheets/rules_engine/images/rules_engine/re_publication
       public/stylesheets/rules_engine/images/rules_engine/re_rule
       public/stylesheets/rules_engine/images/rules_engine/re_workflow
    ).each do |dirname|
      m.empty_directory dirname
    end

    %W(
       config/initializers/rules_engine.rb
       db/migrate/20100308225008_create_rules_engine.rb
       doc/README.rules_engine
       doc/README.rules_engine_view
       public/javascripts/rules_engine/jquery-1.4.2.min.js
       public/javascripts/rules_engine/jquery.autocomplete.pack.js
       public/javascripts/rules_engine/jquery.blockUI.js
       public/javascripts/rules_engine/jquery.fancybox-1.3.1.js
       public/javascripts/rules_engine/re_history_index.js
       public/javascripts/rules_engine/re_history_show.js
       public/javascripts/rules_engine/re_plan_change.js
       public/javascripts/rules_engine/re_plan_new.js
       public/javascripts/rules_engine/re_plan_preview.js
       public/javascripts/rules_engine/re_publication_show.js
       public/javascripts/rules_engine/re_view.js
       public/javascripts/rules_engine/re_workflow_add.js
       public/javascripts/rules_engine/re_workflow_change.js
       public/javascripts/rules_engine/re_workflow_new.js
       public/javascripts/rules_engine/re_workflow_plan.js
       public/javascripts/rules_engine/re_workflow_preview.js
       public/javascripts/rules_engine/re_workflow_show.js
       public/stylesheets/application.css
       public/stylesheets/rules_engine/blueprint/ie.css
       public/stylesheets/rules_engine/blueprint/plugins/buttons/icons/cross.png
       public/stylesheets/rules_engine/blueprint/plugins/buttons/icons/key.png
       public/stylesheets/rules_engine/blueprint/plugins/buttons/icons/tick.png
       public/stylesheets/rules_engine/blueprint/plugins/buttons/readme.txt
       public/stylesheets/rules_engine/blueprint/plugins/buttons/screen.css
       public/stylesheets/rules_engine/blueprint/plugins/fancy-type/readme.txt
       public/stylesheets/rules_engine/blueprint/plugins/fancy-type/screen.css
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/doc.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/email.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/external.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/feed.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/im.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/pdf.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/visited.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/icons/xls.png
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/readme.txt
       public/stylesheets/rules_engine/blueprint/plugins/link-icons/screen.css
       public/stylesheets/rules_engine/blueprint/plugins/rtl/readme.txt
       public/stylesheets/rules_engine/blueprint/plugins/rtl/screen.css
       public/stylesheets/rules_engine/blueprint/print.css
       public/stylesheets/rules_engine/blueprint/screen.css
       public/stylesheets/rules_engine/blueprint/src/forms.css
       public/stylesheets/rules_engine/blueprint/src/grid.css
       public/stylesheets/rules_engine/blueprint/src/grid.png
       public/stylesheets/rules_engine/blueprint/src/ie.css
       public/stylesheets/rules_engine/blueprint/src/print.css
       public/stylesheets/rules_engine/blueprint/src/reset.css
       public/stylesheets/rules_engine/blueprint/src/typography.css
       public/stylesheets/rules_engine/fancybox/blank.gif
       public/stylesheets/rules_engine/fancybox/fancy_close.png
       public/stylesheets/rules_engine/fancybox/fancy_loading.png
       public/stylesheets/rules_engine/fancybox/fancy_nav_left.png
       public/stylesheets/rules_engine/fancybox/fancy_nav_right.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_e.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_n.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_ne.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_nw.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_s.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_se.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_sw.png
       public/stylesheets/rules_engine/fancybox/fancy_shadow_w.png
       public/stylesheets/rules_engine/fancybox/fancy_title_left.png
       public/stylesheets/rules_engine/fancybox/fancy_title_main.png
       public/stylesheets/rules_engine/fancybox/fancy_title_over.png
       public/stylesheets/rules_engine/fancybox/fancy_title_right.png
       public/stylesheets/rules_engine/fancybox/fancybox-x.png
       public/stylesheets/rules_engine/fancybox/fancybox-y.png
       public/stylesheets/rules_engine/fancybox/fancybox.png
       public/stylesheets/rules_engine/fancybox/jquery.fancybox-1.3.1.css
       public/stylesheets/rules_engine/images/re_view_box/shadowbox.png
       public/stylesheets/rules_engine/images/re_view_box/whitebox.jpg
       public/stylesheets/rules_engine/images/re_view_button/checked-off.gif
       public/stylesheets/rules_engine/images/re_view_button/checked-on.gif
       public/stylesheets/rules_engine/images/re_view_button/icon-add.png
       public/stylesheets/rules_engine/images/re_view_button/icon-delete.png
       public/stylesheets/rules_engine/images/re_view_button/list-add.png
       public/stylesheets/rules_engine/images/re_view_button/list-remove.png
       public/stylesheets/rules_engine/images/re_view_button/list-select.png
       public/stylesheets/rules_engine/images/re_view_button/oval-blue-left.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-blue-right.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-gray-left.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-gray-right.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-green-left.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-green-right.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-orange-left.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-orange-right.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-red-left.gif
       public/stylesheets/rules_engine/images/re_view_button/oval-red-right.gif
       public/stylesheets/rules_engine/images/re_view_error/re-alert-close.png
       public/stylesheets/rules_engine/images/re_view_navigate/breadcrumb.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/list-next-disabled-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/list-next-enabled-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/list-prev-disabled-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/list-prev-enabled-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/loading.gif
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-changed-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-changed-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-draft-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-draft-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-error-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-info-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-published-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-published-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-success-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-valid-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-valid-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-verify-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-verify-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_common/status-verify-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_history/error-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_history/info-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_history/list-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_history/success-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/alert-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/change-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/copy-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/delete-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/edit-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/list-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/new-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/preview-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/publish-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/revert-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/show-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/title-plural.png
       public/stylesheets/rules_engine/images/rules_engine/re_plan/title-single.png
       public/stylesheets/rules_engine/images/rules_engine/re_publication/show-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/add-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/alert-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/destroy-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/edit-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/error-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/help-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/help-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/icon-ad-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/move-down-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/move-down-off-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/move-up-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/move-up-off-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/new-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/next-down-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/next-right-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/show-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/start-pipeline-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/stop-failure-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/stop-success-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/title-plural.png
       public/stylesheets/rules_engine/images/rules_engine/re_rule/title-single.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/add-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/add-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/add-off-14.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/alert-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/change-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/change-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/copy-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/delete-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/edit-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/is-default-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/list-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/make-default-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/make-default-off-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/new-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/plan-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/preview-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/remove-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/show-18.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/show-25.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/title-plural.png
       public/stylesheets/rules_engine/images/rules_engine/re_workflow/title-single.png
       public/stylesheets/rules_engine/jquery.autocomplete.css
       public/stylesheets/rules_engine/rules_engine.css
       public/stylesheets/rules_engine/screen.css
    ).each do |filename|
      m.copy_file filename, filename
    end


  end
end
