directories :
  - app/rules
  - spec/lib/rules
  - lib/tasks

templates :
  replacements :
    - simple : rule_name
    - Simple : rule_class
    
  directories : 
    - app/views/re_rule_definitions/simple_rule

  files : 
    - app/rules/simple_rule.rb
    - app/views/re_rule_definitions/simple_rule/_edit.html.erb
    - app/views/re_rule_definitions/simple_rule/_help.html.erb
    - app/views/re_rule_definitions/simple_rule/_new.html.erb
    - app/views/re_rule_definitions/simple_rule/_form.html.erb
    - spec/lib/rules/simple_rule_spec.rb
  
