directories :
  - app/rules
  - spec/lib/rules
  - lib/tasks

templates :
  replacements :
    - rule_simple : rule_name
    - RuleSimple : rule_class
    
  directories : 
    - app/views/re_rule_definitions/rule_simple

  files : 
    - app/rules/rule_simple.rb
    - app/views/re_rule_definitions/rule_simple/_edit.html.erb
    - app/views/re_rule_definitions/rule_simple/_help.html.erb
    - app/views/re_rule_definitions/rule_simple/_new.html.erb
    - app/views/re_rule_definitions/rule_simple/_form.html.erb
    - spec/lib/rules/rule_simple_spec.rb
  
