class RulesEngineManifest
  def self.populate_record(m)

    %W(
      app/controllers
      app/helpers
      app/models
      app/views/layouts
      app/views/re_jobs
      app/views/re_pipeline_jobs
      app/views/re_pipelines
      app/views/re_rules
      db/migrate
      doc
      features/re_pipeline
      features/step_definitions/common
      features/support
      lib/tasks
      public/images/re_job
      public/images/re_pipeline
      public/images/re_rule
      public/images/re_rule_class
      public/javascripts
      public/stylesheets
      public/stylesheets/blueprint
      public/stylesheets/blueprint/plugins
      public/stylesheets/blueprint/plugins/buttons
      public/stylesheets/blueprint/plugins/buttons/icons
      public/stylesheets/blueprint/plugins/fancy-type
      public/stylesheets/blueprint/plugins/link-icons
      public/stylesheets/blueprint/plugins/link-icons/icons
      public/stylesheets/blueprint/plugins/rtl
      public/stylesheets/blueprint/src
      public/stylesheets/fancybox
      public/stylesheets/re_view_box
      public/stylesheets/re_view_button
      public/stylesheets/re_view_navigate
      spec/controllers
      spec/helpers
      spec/models
      spec/support
    ).each do |dirname|
      m.directory dirname
    end

    %W(
      app/controllers/re_jobs_controller.rb
      app/controllers/re_pipeline_jobs_controller.rb
      app/controllers/re_pipelines_controller.rb
      app/controllers/re_rules_controller.rb
      app/helpers/re_pipeline_helper.rb
      app/models/re_job.rb
      app/models/re_job_audit.rb
      app/models/re_pipeline.rb
      app/models/re_pipeline_activated.rb
      app/models/re_pipeline_activated_observer.rb
      app/models/re_pipeline_base.rb
      app/models/re_rule.rb
      app/models/re_rule_expected_outcome.rb
      app/views/layouts/rules_engine.html.erb
      app/views/re_jobs/_empty.html.erb
      app/views/re_jobs/_index_large.html.erb
      app/views/re_jobs/_index_small.html.erb
      app/views/re_jobs/_show.html.erb
      app/views/re_jobs/index.html.erb
      app/views/re_jobs/index.js.erb
      app/views/re_jobs/show.html.erb
      app/views/re_jobs/show.js.erb
      app/views/re_pipeline_jobs/index.html.erb
      app/views/re_pipeline_jobs/index.js.erb
      app/views/re_pipelines/_change.html.erb
      app/views/re_pipelines/_change_actions.html.erb
      app/views/re_pipelines/_confirm.html.erb
      app/views/re_pipelines/_edit.html.erb
      app/views/re_pipelines/_empty.html.erb
      app/views/re_pipelines/_index.html.erb
      app/views/re_pipelines/_new.html.erb
      app/views/re_pipelines/_show.html.erb
      app/views/re_pipelines/change.html.erb
      app/views/re_pipelines/create.js.erb
      app/views/re_pipelines/edit.html.erb
      app/views/re_pipelines/edit.js.erb
      app/views/re_pipelines/index.html.erb
      app/views/re_pipelines/new.html.erb
      app/views/re_pipelines/new.js.erb
      app/views/re_pipelines/show.html.erb
      app/views/re_pipelines/template.html.erb
      app/views/re_pipelines/update.js.erb
      app/views/re_rules/_change.html.erb
      app/views/re_rules/_edit.html.erb
      app/views/re_rules/_empty.html.erb
      app/views/re_rules/_empty.js.erb
      app/views/re_rules/_error.html.erb
      app/views/re_rules/_help.html.erb
      app/views/re_rules/_index.html.erb
      app/views/re_rules/_menu.html.erb
      app/views/re_rules/_new.html.erb
      app/views/re_rules/_show.html.erb
      app/views/re_rules/destroy.js.erb
      app/views/re_rules/edit.html.erb
      app/views/re_rules/edit.js.erb
      app/views/re_rules/error.html.erb
      app/views/re_rules/error.js.erb
      app/views/re_rules/help.html.erb
      app/views/re_rules/help.js.erb
      app/views/re_rules/new.html.erb
      app/views/re_rules/new.js.erb
      app/views/re_rules/update.js.erb
      db/migrate/20100308225008_create_re_pipelines.rb
      doc/README.rules_engine
      doc/README.rules_engine_features
      doc/README.rules_engine_view
      features/re_pipeline/lookup.feature
      features/step_definitions/common/re_debug_steps.rb
      features/step_definitions/common/re_error_steps.rb
      features/step_definitions/common/re_form_steps.rb
      features/step_definitions/common/re_model_steps.rb
      features/step_definitions/common/re_user_steps.rb
      features/step_definitions/common/re_view_steps.rb
      features/support/blueprint_re_pipelines.rb
      features/support/rules_engine.rb
      lib/tasks/re_execute.rake
      public/images/re_job/error-14.png
      public/images/re_job/error-18.png
      public/images/re_job/error-25.png
      public/images/re_job/error-48.png
      public/images/re_job/goto-16.png
      public/images/re_job/info-14.png
      public/images/re_job/info-18.png
      public/images/re_job/info-25.png
      public/images/re_job/info-48.png
      public/images/re_job/list-14.png
      public/images/re_job/list-18.png
      public/images/re_job/list-25.png
      public/images/re_job/list-48.png
      public/images/re_job/loadingAnimation.gif
      public/images/re_job/next-disabled-14.png
      public/images/re_job/next-disabled-18.png
      public/images/re_job/next-disabled-25.png
      public/images/re_job/next-disabled-48.png
      public/images/re_job/next-enabled-14.png
      public/images/re_job/next-enabled-18.png
      public/images/re_job/next-enabled-25.png
      public/images/re_job/next-enabled-48.png
      public/images/re_job/prev-disabled-14.png
      public/images/re_job/prev-disabled-18.png
      public/images/re_job/prev-disabled-25.png
      public/images/re_job/prev-disabled-48.png
      public/images/re_job/prev-enabled-14.png
      public/images/re_job/prev-enabled-18.png
      public/images/re_job/prev-enabled-25.png
      public/images/re_job/prev-enabled-48.png
      public/images/re_job/success-14.png
      public/images/re_job/success-18.png
      public/images/re_job/success-25.png
      public/images/re_job/success-48.png
      public/images/re_pipeline/__destroy-14.png
      public/images/re_pipeline/__destroy-18.png
      public/images/re_pipeline/__destroy-25.png
      public/images/re_pipeline/__destroy-48.png
      public/images/re_pipeline/activate-14.png
      public/images/re_pipeline/activate-18.png
      public/images/re_pipeline/activate-25.png
      public/images/re_pipeline/activate-48.png
      public/images/re_pipeline/alert-14.png
      public/images/re_pipeline/alert-18.png
      public/images/re_pipeline/alert-25.png
      public/images/re_pipeline/alert-48.png
      public/images/re_pipeline/change-14.png
      public/images/re_pipeline/change-18.png
      public/images/re_pipeline/change-25.png
      public/images/re_pipeline/change-48.png
      public/images/re_pipeline/changed-14.png
      public/images/re_pipeline/changed-18.png
      public/images/re_pipeline/changed-25.png
      public/images/re_pipeline/changed-48.png
      public/images/re_pipeline/current-14.png
      public/images/re_pipeline/current-18.png
      public/images/re_pipeline/current-25.png
      public/images/re_pipeline/current-48.png
      public/images/re_pipeline/deactivate-14.png
      public/images/re_pipeline/deactivate-18.png
      public/images/re_pipeline/deactivate-25.png
      public/images/re_pipeline/deactivate-48.png
      public/images/re_pipeline/destroy-14.png
      public/images/re_pipeline/destroy-18.png
      public/images/re_pipeline/destroy-25.png
      public/images/re_pipeline/destroy-48.png
      public/images/re_pipeline/draft-14.png
      public/images/re_pipeline/draft-18.png
      public/images/re_pipeline/draft-25.png
      public/images/re_pipeline/draft-48.png
      public/images/re_pipeline/edit-14.png
      public/images/re_pipeline/edit-18.png
      public/images/re_pipeline/edit-25.png
      public/images/re_pipeline/edit-48.png
      public/images/re_pipeline/list-14.png
      public/images/re_pipeline/list-18.png
      public/images/re_pipeline/list-25.png
      public/images/re_pipeline/list-48.png
      public/images/re_pipeline/list-down.png
      public/images/re_pipeline/list-right.png
      public/images/re_pipeline/new-14.png
      public/images/re_pipeline/new-18.png
      public/images/re_pipeline/new-25.png
      public/images/re_pipeline/new-48.png
      public/images/re_pipeline/revert-14.png
      public/images/re_pipeline/revert-18.png
      public/images/re_pipeline/revert-25.png
      public/images/re_pipeline/revert-48.png
      public/images/re_pipeline/show-14.png
      public/images/re_pipeline/show-18.png
      public/images/re_pipeline/show-25.png
      public/images/re_pipeline/show-48.png
      public/images/re_pipeline/verify-14.png
      public/images/re_pipeline/verify-18.png
      public/images/re_pipeline/verify-25.png
      public/images/re_pipeline/verify-48.png
      public/images/re_rule/__destroy-14.png
      public/images/re_rule/__destroy-18.png
      public/images/re_rule/__destroy-25.png
      public/images/re_rule/__destroy-48.png
      public/images/re_rule/destroy-14.png
      public/images/re_rule/destroy-18.png
      public/images/re_rule/destroy-25.png
      public/images/re_rule/destroy-48.png
      public/images/re_rule/edit-14.png
      public/images/re_rule/edit-18.png
      public/images/re_rule/edit-25.png
      public/images/re_rule/edit-48.png
      public/images/re_rule/goto-pipeline-14.png
      public/images/re_rule/goto-pipeline-18.png
      public/images/re_rule/move-down-14.png
      public/images/re_rule/move-down-18.png
      public/images/re_rule/move-down-25.png
      public/images/re_rule/move-down-48.png
      public/images/re_rule/move-down-off-14.png
      public/images/re_rule/move-down-off-18.png
      public/images/re_rule/move-down-off-25.png
      public/images/re_rule/move-down-off-48.png
      public/images/re_rule/move-up-14.png
      public/images/re_rule/move-up-18.png
      public/images/re_rule/move-up-25.png
      public/images/re_rule/move-up-48.png
      public/images/re_rule/move-up-off-14.png
      public/images/re_rule/move-up-off-18.png
      public/images/re_rule/move-up-off-25.png
      public/images/re_rule/move-up-off-48.png
      public/images/re_rule/next-change-14.png
      public/images/re_rule/next-change-18.png
      public/images/re_rule/next-change-25.png
      public/images/re_rule/next-change-48.png
      public/images/re_rule/next-show-14.png
      public/images/re_rule/next-show-18.png
      public/images/re_rule/next-show-25.png
      public/images/re_rule/next-show-48.png
      public/images/re_rule/stop-failure-14.png
      public/images/re_rule/stop-failure-18.png
      public/images/re_rule/stop-failure-25.png
      public/images/re_rule/stop-failure-48.png
      public/images/re_rule/stop-success-14.png
      public/images/re_rule/stop-success-18.png
      public/images/re_rule/stop-success-25.png
      public/images/re_rule/stop-success-48.png
      public/images/re_rule/valid-14.png
      public/images/re_rule/valid-18.png
      public/images/re_rule/valid-25.png
      public/images/re_rule/valid-48.png
      public/images/re_rule/verify-14.png
      public/images/re_rule/verify-18.png
      public/images/re_rule/verify-25.png
      public/images/re_rule/verify-48.png
      public/images/re_rule_class/add-14.png
      public/images/re_rule_class/add-18.png
      public/images/re_rule_class/add-25.png
      public/images/re_rule_class/add-48.png
      public/images/re_rule_class/help-14.png
      public/images/re_rule_class/help-18.png
      public/images/re_rule_class/help-25.png
      public/images/re_rule_class/help-48.png
      public/images/re_rule_class/list-down.png
      public/images/re_rule_class/list-right.png
      public/images/re_rule_class/new-14.png
      public/images/re_rule_class/new-18.png
      public/images/re_rule_class/new-25.png
      public/images/re_rule_class/new-48.png
      public/javascripts/jquery-1.4.2.min.js
      public/javascripts/jquery.autocomplete.pack.js
      public/javascripts/jquery.blockUI.js
      public/javascripts/jquery.fancybox-1.3.1.js
      public/javascripts/re_job_index.js
      public/javascripts/re_pipeline_change.js
      public/javascripts/re_pipeline_index.js
      public/javascripts/re_pipeline_index_jobs.js
      public/javascripts/re_pipeline_new.js
      public/javascripts/re_pipeline_show_jobs.js
      public/javascripts/re_view.js
      public/stylesheets/blueprint/ie.css
      public/stylesheets/blueprint/plugins/buttons/icons/cross.png
      public/stylesheets/blueprint/plugins/buttons/icons/key.png
      public/stylesheets/blueprint/plugins/buttons/icons/tick.png
      public/stylesheets/blueprint/plugins/buttons/readme.txt
      public/stylesheets/blueprint/plugins/buttons/screen.css
      public/stylesheets/blueprint/plugins/fancy-type/readme.txt
      public/stylesheets/blueprint/plugins/fancy-type/screen.css
      public/stylesheets/blueprint/plugins/link-icons/icons/doc.png
      public/stylesheets/blueprint/plugins/link-icons/icons/email.png
      public/stylesheets/blueprint/plugins/link-icons/icons/external.png
      public/stylesheets/blueprint/plugins/link-icons/icons/feed.png
      public/stylesheets/blueprint/plugins/link-icons/icons/im.png
      public/stylesheets/blueprint/plugins/link-icons/icons/pdf.png
      public/stylesheets/blueprint/plugins/link-icons/icons/visited.png
      public/stylesheets/blueprint/plugins/link-icons/icons/xls.png
      public/stylesheets/blueprint/plugins/link-icons/readme.txt
      public/stylesheets/blueprint/plugins/link-icons/screen.css
      public/stylesheets/blueprint/plugins/rtl/readme.txt
      public/stylesheets/blueprint/plugins/rtl/screen.css
      public/stylesheets/blueprint/print.css
      public/stylesheets/blueprint/screen.css
      public/stylesheets/blueprint/src/forms.css
      public/stylesheets/blueprint/src/grid.css
      public/stylesheets/blueprint/src/grid.png
      public/stylesheets/blueprint/src/ie.css
      public/stylesheets/blueprint/src/print.css
      public/stylesheets/blueprint/src/reset.css
      public/stylesheets/blueprint/src/typography.css
      public/stylesheets/fancybox/blank.gif
      public/stylesheets/fancybox/fancy_close.png
      public/stylesheets/fancybox/fancy_loading.png
      public/stylesheets/fancybox/fancy_nav_left.png
      public/stylesheets/fancybox/fancy_nav_right.png
      public/stylesheets/fancybox/fancy_shadow_e.png
      public/stylesheets/fancybox/fancy_shadow_n.png
      public/stylesheets/fancybox/fancy_shadow_ne.png
      public/stylesheets/fancybox/fancy_shadow_nw.png
      public/stylesheets/fancybox/fancy_shadow_s.png
      public/stylesheets/fancybox/fancy_shadow_se.png
      public/stylesheets/fancybox/fancy_shadow_sw.png
      public/stylesheets/fancybox/fancy_shadow_w.png
      public/stylesheets/fancybox/fancy_title_left.png
      public/stylesheets/fancybox/fancy_title_main.png
      public/stylesheets/fancybox/fancy_title_over.png
      public/stylesheets/fancybox/fancy_title_right.png
      public/stylesheets/fancybox/fancybox-x.png
      public/stylesheets/fancybox/fancybox-y.png
      public/stylesheets/fancybox/fancybox.png
      public/stylesheets/fancybox/jquery.fancybox-1.3.1.css
      public/stylesheets/jquery.autocomplete.css
      public/stylesheets/re_view.css
      public/stylesheets/re_view_box.css
      public/stylesheets/re_view_box/accept.png
      public/stylesheets/re_view_box/exclamation.png
      public/stylesheets/re_view_box/shadowbox.jpg
      public/stylesheets/re_view_box/shadowbox.png
      public/stylesheets/re_view_box/whitebox.jpg
      public/stylesheets/re_view_button.css
      public/stylesheets/re_view_button/checked-off.gif
      public/stylesheets/re_view_button/checked-on.gif
      public/stylesheets/re_view_button/icon-add.png
      public/stylesheets/re_view_button/icon-delete.png
      public/stylesheets/re_view_button/oval-blue-left.gif
      public/stylesheets/re_view_button/oval-blue-right.gif
      public/stylesheets/re_view_button/oval-gray-left.gif
      public/stylesheets/re_view_button/oval-gray-right.gif
      public/stylesheets/re_view_button/oval-green-left.gif
      public/stylesheets/re_view_button/oval-green-right.gif
      public/stylesheets/re_view_button/oval-orange-left.gif
      public/stylesheets/re_view_button/oval-orange-right.gif
      public/stylesheets/re_view_button/oval-red-left.gif
      public/stylesheets/re_view_button/oval-red-right.gif
      public/stylesheets/re_view_error.css
      public/stylesheets/re_view_form.css
      public/stylesheets/re_view_navigate.css
      public/stylesheets/re_view_navigate/breadcrumb.png
      public/stylesheets/re_view_table.css
      public/stylesheets/rules_engine.css
      spec/controllers/re_jobs_controller_spec.rb
      spec/controllers/re_pipeline_jobs_controller_spec.rb
      spec/controllers/re_pipelines_controller_spec.rb
      spec/controllers/re_rules_controller_spec.rb
      spec/helpers/re_pipeline_helper_spec.rb
      spec/models/re_job_audit_spec.rb
      spec/models/re_job_spec.rb
      spec/models/re_pipeline_activated_observer_spec.rb
      spec/models/re_pipeline_activated_spec.rb
      spec/models/re_pipeline_base_spec.rb
      spec/models/re_pipeline_spec.rb
      spec/models/re_rule_expected_outcome_spec.rb
      spec/models/re_rule_spec.rb
      spec/support/rules_engine_macros.rb
    ).each do |filename|
      m.file filename, filename
    end


  end
end
